# roles/launch_proxy/tasks/main.yml
---
- name: Launch Reverse Proxy
  docker_container:
    name: my-httpd
    image: lstiffel/new-httpd:1.0
    pull: true          # <-- Force Ansible à chercher la nouvelle image sur DockerHub
    force_kill: true    # <-- Force à recréer le conteneur si besoin
    restart_policy: unless-stopped
    ports:
      - "80:80"
    networks:
      - name: proxy-network