# roles/launch_proxy/tasks/main.yml
---
- name: Launch Reverse Proxy
  docker_container:
    name: my-httpd
    image: lstiffel/my-httpd:latest
    pull: always          # <-- Force Ansible à chercher la nouvelle image sur DockerHub
    force_kill: true    # <-- Force à recréer le conteneur si besoin
    restart_policy: unless-stopped
    env:
      BACKEND_HOST: "{{ BACKEND_HOST }}"
    ports:
      - "80:80"
    networks:
      - name: proxy-network